import jsPDF from 'jspdf';
import { ZakatResult } from './zakatEngine';
import { PurificationResult } from './purificationEngine';
import { Authority, getAuthorityDisplayName } from './authority';

export interface ExportData {
  zakat?: ZakatResult;
  purification?: PurificationResult;
  authority: Authority;
  date: string;
  inputs?: any;
}

export function exportToPDF(data: ExportData, config?: { logo?: string; primaryColor?: string }): void {
  const doc = new jsPDF();
  const primaryColor = config?.primaryColor || '#C9A24D';
  
  // Helper to convert hex to RGB
  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result
      ? {
          r: parseInt(result[1], 16),
          g: parseInt(result[2], 16),
          b: parseInt(result[3], 16),
        }
      : { r: 201, g: 162, b: 77 };
  };
  
  const rgb = hexToRgb(primaryColor);
  
  // Header
  doc.setFillColor(rgb.r, rgb.g, rgb.b);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Zakat & Purification Report', 105, 20, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  let yPos = 40;
  
  // Date and Authority
  doc.text(`Date: ${data.date}`, 20, yPos);
  doc.text(`Authority: ${getAuthorityDisplayName(data.authority)}`, 20, yPos + 10);
  
  yPos += 25;
  
  // Zakat Section
  if (data.zakat) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Zakat Calculation', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    doc.text(`Zakatable Assets: ${data.zakat.zakatable.toFixed(2)}`, 25, yPos);
    yPos += 7;
    doc.text(`Nisab: ${data.zakat.nisab.toFixed(2)}`, 25, yPos);
    yPos += 7;
    doc.text(`Nisab Met: ${data.zakat.nisabMet ? 'Yes' : 'No'}`, 25, yPos);
    yPos += 7;
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Zakat Amount: ${data.zakat.zakat.toFixed(2)}`, 25, yPos);
    yPos += 10;
    
    doc.setFont('helvetica', 'normal');
    doc.text('Breakdown:', 25, yPos);
    yPos += 7;
    doc.text(`  Cash: ${data.zakat.breakdown.cash.toFixed(2)}`, 30, yPos);
    yPos += 7;
    doc.text(`  Gold: ${data.zakat.breakdown.gold.toFixed(2)}`, 30, yPos);
    yPos += 7;
    doc.text(`  Silver: ${data.zakat.breakdown.silver.toFixed(2)}`, 30, yPos);
    yPos += 7;
    doc.text(`  Investments: ${data.zakat.breakdown.investments.toFixed(2)}`, 30, yPos);
    yPos += 7;
    doc.text(`  Business Assets: ${data.zakat.breakdown.businessAssets.toFixed(2)}`, 30, yPos);
    yPos += 7;
    doc.text(`  Liabilities: ${data.zakat.breakdown.liabilities.toFixed(2)}`, 30, yPos);
    yPos += 15;
  }
  
  // Purification Section
  if (data.purification) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Purification Calculation', 20, yPos);
    yPos += 10;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Profit: $${data.purification.profit.toFixed(2)}`, 25, yPos);
    yPos += 7;
    doc.text(`Average Haram Ratio: ${data.purification.haramRatio.toFixed(2)}%`, 25, yPos);
    yPos += 7;
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Purification Amount: $${data.purification.purification.toFixed(2)}`, 25, yPos);
    yPos += 15;
  }
  
  // Total
  if (data.zakat && data.purification) {
    const total = data.zakat.zakat + data.purification.purification;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setFillColor(rgb.r, rgb.g, rgb.b);
    doc.rect(20, yPos - 5, 170, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text(`Total Payable: $${total.toFixed(2)}`, 105, yPos + 5, { align: 'center' });
  }
  
  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Zakat & Purification Calculator', 105, 285, { align: 'center' });
  
  // Save
  doc.save(`zakat-report-${data.date.replace(/\//g, '-')}.pdf`);
}


